[project]
name = "mesmots"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard-no-fastapi-cloud-cli]>=0.128.0",
    "orjson>=3.11.6",
    "polars>=1.37.1",
    "simpleeval>=1.0.3",
]
