[project]
name = "mesmots"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bottle>=0.13.4",
    "polars>=1.37.1",
    "requests>=2.32.5",
    "simpleeval>=1.0.3",
]
